### ISSUE TITLE
MEGA TO DRIVE TRANSFER BOT

### ISSUE THREAD

**Issue by mirrorclone** [whitehatjrchintu/mega-to-gdrive-bot#2]
LINK

https://github.com/cheems/Mega-to-Google-Drive

Hi brother, I'm writing to give you an idea..

there is a way to transfer a drive directly without downloading the mega nz link..

if you study the script I threw at you, it is possible

all you have to do is adapt this script to the telegram bot and add premium account support..

google drive to google drive clone looks like fire transfer is fast

**Comment by whitehatjrchintu** [comment]
it does the same thing..its a telegram bot and you are talking about google colab.
